In [38]:
import numpy as np
from sklearn import datasets as ds
from sklearn.model_selection import train_test_split # split dataset into train and test sets

# 1. Data preparation
iris = ds.load_iris()
X = iris.data # feature vectors
y = iris.target

print(X.shape, y.shape)
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size = 0.2) # test_size % of test set

print('training set', X_train.shape, y_train.shape)
print('test set', X_test.shape, y_test.shape)

(150, 4) (150,)
training set (120, 4) (120,)
test set (30, 4) (30,)


In [39]:
# 2. Model training
# KNN is an instance-based algorithm, and 
# it does not have the actual training


In [40]:
def Prediction(X_input, X_Train, k=5):
    '''
        X_input: n*4 new data samples
        X_train, 
    '''
    y_pred = np.zeros((X_input.shape[0]))
    for i, x in enumerate(X_input):
        k_inx = findKNgbs(x,X_Train,k)
        K_labels = y_train[k_inx]
        counts = np.bincount(K_labels.reshape((k,)), minlength=2)
        y_pred[i]= np.argmax(counts)
    return y_pred.astype(int)

x_in = X_test[:10]
y_pred = Prediction(x_in, X_train)
print(y_pred)
print(y_test[:10])


    

[2 2 1 1 1 2 2 0 2 1]
[2 2 1 1 1 1 2 0 2 1]


In [41]:
#Calculate error rate
def error_rate(y_pred, y_true):
    return np.sum((y_true != y_pred)) / y_true.shape[0]
error_rate(y_pred, y_test[:2])


/tmp/ipykernel_2913/1551448293.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  return np.sum((y_true != y_pred)) / y_true.shape[0]


0.5

In [42]:
# 3. Prediction and evaluation
# evaluation metric: error rate : % of data samples missclassified

# prediction: 1) find the K nearest neighbors; 2)voting to predict

In [43]:
#1) find the k nns for an input data sample
def findKNgbs(x_star, X_train, K = 5):
    '''find K nearest neighbors for a given data sample in X_train
        
        input:
            x_star: new data sample. Shape 1 by 4
            X_train:
        return:
            K nearest neighbors
    '''
    # calculate the Euclidean distance 
    n = X_train.shape[0] # number of data samples in X_train
    dis = np.zeros((n, 1)) # initialize n 0 distances
    inx = 0
    for x in X_train:
        d = np.sqrt(np.sum((x_star-x)*(x_star-x)))
        dis[inx] = d
        inx = inx + 1
        
    # find the k nearest neighbors using a sorting algorithm
    ind = np.argsort(dis, axis = 0)
    
    return ind[:K] # return the indices for the K nns

x_star = X_test[0]
print(x_star)
k_inx = findKNgbs(x_star, X_train, K=5)
print(k_inx)

Prediction(x_star, X_train, k=5)

[6.7 2.5 5.8 1.8]
[[105]
 [107]
 [ 86]
 [ 12]
 [ 50]]


array([2, 1, 2, 0])

In [44]:
# prediction
# check the class lables of the k nns
k_labels = y_train[k_inx]
print(k_labels)
#print(k_labels.reshape(5,))

counts = np.bincount(k_labels.reshape((5,)), minlength = 2)
print(counts)

y_pred =np.argmax(counts)
print('the prediction is', y_pred)

[[2]
 [2]
 [2]
 [2]
 [2]]
[0 0 5]
the prediction is 2


In [45]:
# afterclass practice
#1. how do we calculate the predictions for all test data samples


#2. calculate the error rate on the test set
# try to use differnt K


In [46]:
#4. model persistance



In [50]:
for k in range(1,100,2):
    y_pred=Prediction(X_test, X_train, k)
    er =  error_rate(y_pred, y_test)
    print(er)

0.03333333333333333
0.03333333333333333
0.03333333333333333
0.03333333333333333
0.03333333333333333
0.03333333333333333
0.03333333333333333
0.03333333333333333
0.03333333333333333
0.03333333333333333
0.03333333333333333
0.03333333333333333
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.06666666666666667
0.1
0.1
0.13333333333333333
0.1
0.26666666666666666
0.23333333333333334
0.23333333333333334
0.43333333333333335
0.4666666666666667
0.5333333333333333
0.5333333333333333
0.5333333333333333
0.5333333333333333
0.5666666666666667
0.5666666666666667
0.5666666666666667
0.5666666666666667
0.5666666666666667
0.5666666666666667
0.5666666666666667
0.5666666666666667
0.5666666666666667
0.5666666666666667
0.5666666666666667
